name: Module Builder

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-notes: ${{ steps.set-release-notes.outputs.release-notes }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Release Notes for Github
        id: set-release-notes-github
        run: |
          echo "**A ton of work when into this update. If you use my module and are able to donate, it is much appreciated!**" >> release_notes.txt
          echo "**There were far too many changes to give a comprehensive list here, almost every single automation was touched in some way with many requiring extensive reworks, this will be a general overview. There are a handful of official 5e automations that do not work currently awaiting a Midi or Sequencer update: Stroke of Luck, Scatter, Armor of Hexes. If you find a bug, please post it to the relevant discord Automations thread or Github. This release should be compatible with the newly released 5e 3.3, but has not been thoroughly tested.**" >> release_notes.txt
          echo "- General:" >> release_notes.txt
          echo "  - Dependencies: Removed dependencies for Warpgate, Dfreds Convenient Effects, Template Macro, Effect Macro, Token Attacher, and Walled Templates. Added dependencies for Bugbears Scripts and Region Attacher." >> release_notes.txt
          echo "  - Automations: Almost every single automation was touched in this rework to some extent. This includes modifications for general support of v12, bugfixes, as well as enhancements to general functionality and in some cases animations. Each official 5e automation was individually tested to try and make this as painless a transition as possible. 3rd party and homebrew automations were not tested as thoroughly, and some are still in progress." >> release_notes.txt
          echo "  - Dialogs: Any non system/midi dialog (ie core GPS dialog) was updated to use GPS core dialog functionality and design language based on Foundrys Dialog V2 framework. The dialogs have also all had a design pass to give a consistent and more professional layout across the board. There are a few homebrew dialogs still awaiting an update" >> release_notes.txt
          echo "  - System Functionality: Thanks to help from Michael, GPS is modifying cores region token testing via libWrapper. With GPS installed, regions will test the edge of a token along with its center point to better align with 5e rules. Native Foundry v12 regions only test a tokens center point. This will be removed if/when the 5e system adapts this change." >> release_notes.txt
          echo "  - Settings Menu: Consolidated the remaining general settings into a General Settings button menu. Added settings for GPS dialog countdown animation type (border vs full bar) and option to allow 3rd party reactions outside of combat. Modified Template Hiding to be a global setting to hide any placed template, note this is not required for Opportunity Attack since it is now region based." >> release_notes.txt
          echo "  - Templates: Any template automation in my module has been converted to use a Region for the automation logic. User placement still occurs via a template with Michaels helpful Region Attacher module, say thanks to Michael!" >> release_notes.txt
          echo "  - Status Effect Application: All status application has been converted to use core which allows toggling of effects from an actor sheet like core natively allows. Midi relevant flags for statuses are maintained via Bugbears Scripts, say thanks to Bugbear! When dfreds ce releases I will probably drop the hard dependency on Bugbears Scripts and have Bugbears Scripts and Dfreds CE as Recommended Modules." >> release_notes.txt
          echo "  - Opportunity Attack: Large re-work to use v12s core regions in place of templates. Added token movement prevention for Sentinel attacks" >> release_notes.txt
          echo "  - Added Zephyr Strike." >> release_notes.txt
          echo "release-notes-github<<EOF" >> $GITHUB_ENV
          cat release_notes.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format Release Notes for Discord
        id: format-release-notes-discord
        run: |
          DISCORD_NOTES=$(awk '{printf "%s\\n", $0}' release_notes.txt | sed 's/\\n$//')
          echo "::set-output name=release-notes-discord::$DISCORD_NOTES"

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ env.release-notes-github }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.zip, ./module.json'
          tag: ${{ steps.get-version.outputs.version }}

      - name: Release Foundry Package
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version" \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.FOUNDRY_API_TOKEN }}" \
          -d '{
            "id": "'"gambits-premades"'",
            "release": {
              "version": "'"${{ steps.get-version.outputs.version }}"'",
              "manifest": "'"https://github.com/gambit07/gambits-premades/releases/latest/download/module.json"'",
              "notes": "'"https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}"'",
              "compatibility": {
                "minimum": "'"12"'",
                "verified": "'"12"'",
                "maximum": "'"12"'"
              }
            }
          }'

      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_MIDI_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
          "embeds": [{
            "title": "Gambit'"'"'s Premades Release: ${{ steps.get-version.outputs.version }}",
            "description": "**To support my continued work on this module!\n<https://ko-fi.com/gambit07> ❤️**\n\n${{ steps.format-release-notes-discord.outputs.release-notes-discord }}\n\nCheck it out through the Foundry package manager or the link below:\n<https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}>",
            "image": {
              "url": "https://avatars.githubusercontent.com/u/4236874?s=400&u=05d3718580ef87ea13467131a0c1fcaf4956630d&v=4"
            }
          }]
          }' $DISCORD_WEBHOOK
