name: Module Builder

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-notes: ${{ steps.set-release-notes.outputs.release-notes }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Release Notes for Github
        id: set-release-notes-github
        run: |
          echo "- Additions: Arcane Archer: Updated to add all Arcane Archer shot types. These are now housed as activities on the Arcane Shot item, you will still need the individual Arrow types (Bursting, Shadow, etc) from my compendium/medkit so that appropriate arrow activities are displayed." >> release_notes.txt
          echo "- Updates:" >> release_notes.txt
          echo "  - Multiple Items: Updated synthetic activity handling to socket the use to the appropriate user where relevant. NOTE: Module now requires Midi 12.4.34 minimum as there were some important bugfixes for socketing activities" >> release_notes.txt
          echo "  - Silvery Barbs: Added activity handling for Save events. Should make them more resilient in the future." >> release_notes.txt
          echo "  - Indomitable: Added activity handling for Save reroll. Should make this more resilient in the future." >> release_notes.txt
          echo "  - Region Wrapping: Update Region Wrapping to use default behavior on square gridded scenes to resolve some intermittent issues with region teleporting." >> release_notes.txt
          echo "  - Opportunity Attack: Added updated region shapes for OA. Gridless now uses a squircle shape, and Hex grids use a hex shape. Added new DAE flags oaImmunity and oaSuppression. oaImmunity can be added to an effect on a token to prevent any opportunity attacks against it. oaSuppression can be added to an effect on a token to prevent it from being able to make any opportunity attacks. NOTE: The old method of looking for a named effect ex. Opportunity Attack Immunity for general immunity or a specific item effect ex. Shocking Grasp will be deprecated in the future, premades or individual automations should use these dae flags moving forward." >> release_notes.txt
          echo "  - Counterspell: Added Subtle Spell casting support. Counterspell will now present a checkbox to the user to use Subtle Spell when present and sorcery points available. If checked, the spell will become un-counterspellable and the appropriate sorcery point will be used." >> release_notes.txt
          echo "  - GPS Dialogs: Added support for Carolingian UI. GPS Dialogs colors will now match color theming from Carolingian if present." >> release_notes.txt
          echo "- Bugfixes:" >> release_notes.txt
          echo "  - Temporal Shunt: Fixed a couple issues and re-worked to use an activity on the roll." >> release_notes.txt
          echo "  - Divine Sense: Fix args itemCardId no longer being found, for some reason." >> release_notes.txt
          echo "  - process3rdPartyReactionDialog: Fixed awaiting reaction generic chat messages not being removed when dialog closed via the top right x button." >> release_notes.txt
          echo "release-notes-github<<EOF" >> $GITHUB_ENV
          cat release_notes.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format Release Notes for Discord
        id: format-release-notes-discord
        run: |
          DISCORD_NOTES=$(awk '{printf "%s\\n", $0}' release_notes.txt | sed 's/\\n$//')
          echo "::set-output name=release-notes-discord::$DISCORD_NOTES"

      - name: Get Version from Commit Message
        id: get-version
        run: |
          version=$(git log -1 --pretty=%B | grep -o -E '[v]?[0-9]+\.[0-9]+\.[0-9]+' | sed 's/^v//')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Extracted version: $version"

      - name: Update module.json with Version
        run: node update-module.js ${{ steps.get-version.outputs.version }}

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./*

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ env.release-notes-github }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.zip, ./module.json'
          tag: ${{ steps.get-version.outputs.version }}

      - name: Release Foundry Package
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version" \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.FOUNDRY_API_TOKEN }}" \
          -d '{
            "id": "'"gambits-premades"'",
            "release": {
              "version": "'"${{ steps.get-version.outputs.version }}"'",
              "manifest": "'"https://github.com/gambit07/gambits-premades/releases/download/${{ steps.get-version.outputs.version }}/module.json"'",
              "download": "'"https://github.com/gambit07/gambits-premades/releases/download/${{ steps.get-version.outputs.version }}/module.zip"'",
              "notes": "'"https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}"'",
              "compatibility": {
                "minimum": "'"12.328"'",
                "verified": "'"12"'",
                "maximum": "'"12"'"
              }
            }
          }'

      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_MIDI_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
          "embeds": [{
            "title": "Gambit'"'"'s Premades Release: ${{ steps.get-version.outputs.version }}",
            "description": "**To support my continued work on this module!\n<https://ko-fi.com/gambit07> ❤️**\n\n${{ steps.format-release-notes-discord.outputs.release-notes-discord }}\n\nCheck it out through the Foundry package manager or the link below:\n<https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}>",
            "image": {
              "url": "https://avatars.githubusercontent.com/u/4236874?s=400&u=05d3718580ef87ea13467131a0c1fcaf4956630d&v=4"
            }
          }]
          }' $DISCORD_WEBHOOK
