name: Module Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-notes: ${{ steps.set-release-notes.outputs.release-notes }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Release Notes
        id: set-release-notes
        run: |
          echo "::set-output name=release-notes::A summary of things that I might post:\n- Bullet point 1\n- Bullet point 2\n- Bullet point 3"

      - name: Convert Release Notes for GitHub
        id: convert-notes
        run: |
          github_notes="${{ steps.set-release-notes.outputs.release-notes }}"
          github_notes="${github_notes//'\\n'/$'\n'}"
          echo "github_notes<<EOF" >> $GITHUB_ENV
          echo -e "${github_notes}" >> $GITHUB_ENV
          echo "EOF"

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ env.github_notes }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.zip, ./module.json'
          tag: ${{ steps.get-version.outputs.version }}

      - name: Release Foundry Package
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version" \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.FOUNDRY_API_TOKEN }}" \
          -d '{
            "id": "'"gambits-premades"'",
            "release": {
              "version": "'"${{ steps.get-version.outputs.version }}"'",
              "manifest": "'"https://github.com/gambit07/gambits-premades/releases/latest/download/module.json"'",
              "notes": "'"https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}"'",
              "compatibility": {
                "minimum": "'"11"'",
                "verified": "'"11"'",
                "maximum": "'"11"'"
              }
            }
          }'

      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
          "embeds": [{
            "title": "Gambit'"'"'s Premades Release: ${{ steps.get-version.outputs.version }}",
            "description": "**To support my continued work on this module!\n<https://ko-fi.com/gambit07> ❤️**\n\n${{ steps.set-release-notes.outputs.release-notes }}\n\nCheck it out here: <https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}>",
            "image": {
              "url": "https://avatars.githubusercontent.com/u/4236874?s=400&u=2f993aedba89921df143b36ba2b511639434b3a4&v=4&s=50"
            }
          }]
          }' $DISCORD_WEBHOOK