name: Module Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Updated: Counterspell - Counterspell is now fully hosted within the module and no longer requires item deployment. It should be much better optimized. Additionally, Counter-Counterspelling now allows party members of the initially counterspelled creature to also cast counterspell. The item should be fully functional now and I'll be working on some additional options in the future to allow some modification around when players/npcs see dialogs based on GM preference.
            Hotfix in .61
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.zip, ./module.json'
          tag: ${{ steps.get-version.outputs.version }}

      - name: Release Foundry Package
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version" \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.FOUNDRY_API_TOKEN }}" \
          -d '{
            "id": "'"gambits-premades"'",
            "release": {
              "version": "'"${{ steps.get-version.outputs.version }}"'",
              "manifest": "'"https://github.com/gambit07/gambits-premades/releases/latest/download/module.json"'",
              "notes": "'"https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}"'",
              "compatibility": {
                "minimum": "'"11"'",
                "verified": "'"11"'",
                "maximum": "'"11"'"
              }
            }
          }'