name: Module Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-notes: ${{ steps.set-release-notes.outputs.release-notes }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Release Notes for Github
        id: set-release-notes-github
        run: |
          echo "- General: GM Mirror Dialog will now sync the state of the pause button across both clients. This addresses an issue where the user could pause their dialog but the GMs would close and complete as No if they did not also pause theirs, or vice versa. Started to generalize some functions throughout automations and cleaned up all of the 3rd party automations to a certain extent." >> release_notes.txt
          echo "- General: Complete settings rework. Item types are now selectable buttons with a list of automations that can be enabled within that item type. Should make navigating much easier. Added Debug option to help with identifying where a 3rd party reaction may be failing." >> release_notes.txt
          echo "- Updates:" >> release_notes.txt
          echo "  - Opportunity Attack: Added custom handling for Booming Blade. Added additional validation for metric vs imperial calculations. Changed setting name for enabling legacy setup (token attacher + drag ruler) to Enable Legacy Template Attachment to reduce confusion. Added a workaround for Walled Templates attachment throwing an error on movement for player characters. Removed Riposte and Sentinel from the Opportunity Attack Item, should make OA deployment lighter. Added check to prevent enabling/disabling OA via settings during combat as it wont actually effect the current combat and can cause downline issues if proper cleanup is not allowed to occur, so the user will receive a message that this must be done outside combat." >> release_notes.txt
          echo "  - Black Tentacles: Remove Warpgate dependency for token movement when restrained." >> release_notes.txt
          echo "  - Heated Body: Updated to be more efficient. Added folders/implementation for Remorhaz and Reduced threat Remorhaz." >> release_notes.txt
          echo "  - Tentacles: Updated to be more efficient." >> release_notes.txt
          echo "  - Sentinel: Item implementation via OA completely removed, can now be enabled in the Module settings. Now uses additional functionality afforded by the module including pause and GM Mirror Dialog" >> release_notes.txt
          echo "  - Maneuvers - Riposte: Item implementation via OA completely removed, can now be enabled in the Module settings. Now uses additional functionality afforded by the module including pause and GM Mirror Dialog" >> release_notes.txt
          echo "  - Indomitable: Item implementation completely removed, can now be enabled in the Module settings. Make sure to update to the latest version of the item as well. Now uses additional functionality afforded by the module including pause and GM Mirror Dialog" >> release_notes.txt
          echo "  - Fighting Style - Protection: Item implementation completely removed, can now be enabled in the Module settings. Make sure to update to the latest version of the item as well. Now uses additional functionality afforded by the module including pause and GM Mirror Dialog" >> release_notes.txt
          echo "- Bugfixes:" >> release_notes.txt
          echo "  - Motivational Speech: Some cleanup of the code and various small bugfixes" >> release_notes.txt
          echo "  - Scatter: A few small issues resolved. Will be looking at migrating the teleport function away from Warpgate in the future." >> release_notes.txt
          echo "  - Cloud of Daggers: A number of bugfixes and cleanup." >> release_notes.txt
          echo "  - Roksjas Husk: A number of bugfixes." >> release_notes.txt
          echo "  - Opportunity Attack: Fixed bug where per turn OA settings would run even if OA was disabled in settings." >> release_notes.txt
          echo "  - Fighting Style - Interception: Added missing proficiency bonus to d10 roll." >> release_notes.txt
          echo "release-notes-github<<EOF" >> $GITHUB_ENV
          cat release_notes.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format Release Notes for Discord
        id: format-release-notes-discord
        run: |
          DISCORD_NOTES=$(awk '{printf "%s\\n", $0}' release_notes.txt | sed 's/\\n$//')
          echo "::set-output name=release-notes-discord::$DISCORD_NOTES"

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ env.release-notes-github }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.zip, ./module.json'
          tag: ${{ steps.get-version.outputs.version }}

      - name: Release Foundry Package
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version" \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.FOUNDRY_API_TOKEN }}" \
          -d '{
            "id": "'"gambits-premades"'",
            "release": {
              "version": "'"${{ steps.get-version.outputs.version }}"'",
              "manifest": "'"https://github.com/gambit07/gambits-premades/releases/latest/download/module.json"'",
              "notes": "'"https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}"'",
              "compatibility": {
                "minimum": "'"11"'",
                "verified": "'"11"'",
                "maximum": "'"11"'"
              }
            }
          }'

      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_MIDI_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
          "embeds": [{
            "title": "Gambit'"'"'s Premades Release: ${{ steps.get-version.outputs.version }}",
            "description": "**To support my continued work on this module!\n<https://ko-fi.com/gambit07> ❤️**\n\n${{ steps.format-release-notes-discord.outputs.release-notes-discord }}\n\nCheck it out through the Foundry package manager or the link below:\n<https://github.com/gambit07/gambits-premades/releases/tag/${{ steps.get-version.outputs.version }}>",
            "image": {
              "url": "https://avatars.githubusercontent.com/u/4236874?s=400&u=05d3718580ef87ea13467131a0c1fcaf4956630d&v=4"
            }
          }]
          }' $DISCORD_WEBHOOK