name: Create Discord Webhook Release

on:
  workflow_run:
    workflows: [Module Builder]
    types:
       - completed

jobs:
 github-releases-to-discord:
  runs-on: ubuntu-latest
  steps:
   - name: Fetch the latest release
     id: get-latest-release
     uses: octokit/request-action@v2.x
     with:
      route: GET /repos/${{ github.repository }}/releases/latest
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   - name: Checkout
     uses: actions/checkout@v3
   - name: Github Releases To Discord
     uses: SethCohen/github-releases-to-discord@v1.13.1
     with:
      webhook_url: ${{ secrets.DISCORD_MIDI_WEBHOOK }}
      username: "Gambits Premades - Release"
      content: ${{ fromJson(steps.get-latest-release.outputs.data).body }}