name: Create Discord Webhook Release

on:
  release:

jobs:
 github-releases-to-discord:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3
   - name: Github Releases To Discord
     uses: SethCohen/github-releases-to-discord@v1.13.1
     with:
      webhook_url: ${{ secrets.DISCORD_MIDI_WEBHOOK }}
      username: "Gambits Premades - Release"